import test from "node:test";
import assert from "node:assert/strict";
import { isSpecial, mergeEpisodeRows, normalizeAniZipEpisode, normalizeJikanEpisode, titleOf } from "../lib/episodes.js";

test("titleOf never produces [object Object]",()=>{assert.equal(titleOf({english:"Town Where Everything Began"}),"Town Where Everything Began");assert.equal(titleOf({romaji:"Shingeki no Kyojin"}),"Shingeki no Kyojin");assert.equal(titleOf({}),"");});
test("normalizes a regular AniZip episode to the lean shape",()=>{const row=normalizeAniZipEpisode({episodeNumber:1,seasonNumber:1,title:{english:"Pilot"},airDateUtc:"2021-01-10T15:00:00Z",image:"https://example.com/1.jpg"});assert.deepEqual(row,{number:1,sourceSeason:1,absoluteEpisodeNumber:0,title:"Pilot",released:"2021-01-10T15:00:00.000Z",thumbnail:"https://example.com/1.jpg"});});
test("rejects explicit special/OVA/ONA classifications",()=>{for(const type of ["special","ova","ona","movie","recap","opening","ending","trailer","credits"])assert.equal(isSpecial({type,episodeNumber:1},"Regular-looking title"),true,type);});
test("rejects TVDB season 0 and AniDB special codes",()=>{assert.equal(isSpecial({seasonNumber:0,episodeNumber:1},"Regular title"),true);assert.equal(isSpecial({episode:"S1",episodeNumber:1},"Regular title"),true);assert.equal(isSpecial({episode:"C1",episodeNumber:1},"Regular title"),true);assert.equal(isSpecial({episode:"T1",episodeNumber:1},"Regular title"),true);});
test("rejects known One Piece side-story/special titles",()=>{for(const title of ["Episode of Nami","Episode of Merry","Episode of Sabo","Fan Letter","Barto's Secret Room"])assert.equal(isSpecial({episodeNumber:1},title),true,title);});
test("preserves legitimate episode titles containing ordinary words",()=>{assert.equal(isSpecial({episodeNumber:1},"The Beginning"),false);assert.equal(isSpecial({episodeNumber:2},"A Special Moment"),false);assert.equal(isSpecial({episodeNumber:3},"Episode 1000 Special Broadcast"),true);});
test("rejects invalid and non-positive episode numbers",()=>{assert.equal(normalizeJikanEpisode({mal_id:0,title:"Bad"}),null);assert.equal(normalizeJikanEpisode({mal_id:-1,title:"Bad"}),null);assert.equal(normalizeJikanEpisode({mal_id:"x",title:"Bad"}),null);});
test("deduplicates AniZip rows by source season and episode",()=>{const rows=mergeEpisodeRows([{episodeNumber:1,seasonNumber:1,title:"Placeholder One"},{episodeNumber:1,seasonNumber:1,title:"Real Title",image:"https://example.com/1.jpg"},{episodeNumber:2,seasonNumber:1,title:"Placeholder Two"}]);assert.equal(rows.length,2);assert.equal(rows[0].title,"Real Title");});
test("omits invalid dates instead of emitting invalid timestamps",()=>{const row=normalizeAniZipEpisode({episodeNumber:1,title:"Undated Episode",airDateUtc:"not-a-date"});assert.equal(row.released,null);});
