import { getCached, setCached, requestJson } from "./http.js";

const ANILIST_URL = "https://graphql.anilist.co";
const JIKAN_URL = "https://api.jikan.moe/v4";
const ANIZIP_URL = "https://api.ani.zip/v1";
const ANILIST_FIELDS = `id idMal format status episodes season seasonYear title{romaji english native} synonyms startDate{year month day} endDate{year month day} relations{edges{relationType node{id idMal format status episodes season seasonYear title{romaji english native} synonyms startDate{year month day} endDate{year month day}}}}`;

export async function getAniListByMal(malId) {
  const key = `al:${malId}`; const cached = getCached(key); if (cached !== undefined) return cached;
  const query = `query($idMal:Int){Media(idMal:$idMal,type:ANIME){${ANILIST_FIELDS}}}`;
  try { const json = await requestJson(ANILIST_URL, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ query, variables: { idMal: Number(malId) } }), retries: 2, cacheKey: key }); return setCached(key, json?.data?.Media || null); } catch { setCached(key, null); return null; }
}
export function aniListToJikan(node) { return node ? { mal_id: Number(node.idMal), type: "TV", episodes: Number(node.episodes) || null, title: node.title?.romaji || node.title?.english || node.title?.native || `MAL ${node.idMal}`, title_english: node.title?.english || null, title_japanese: node.title?.native || null, title_synonyms: Array.isArray(node.synonyms) ? node.synonyms : [], aired: { from: dateParts(node.startDate), to: dateParts(node.endDate) }, year: Number(node.seasonYear) || null } : null; }
function dateParts(x) { return x?.year && x?.month && x?.day ? `${String(x.year).padStart(4,"0")}-${String(x.month).padStart(2,"0")}-${String(x.day).padStart(2,"0")}T00:00:00.000Z` : null; }
export async function getJikanAnime(malId) { const key = `jk:a:${malId}`, cached = getCached(key); if (cached !== undefined) return cached; try { const json = await requestJson(`${JIKAN_URL}/anime/${malId}/full`, { retries: 2, cacheKey: key }); return setCached(key, json?.data || null); } catch { setCached(key, null); return null; } }
export async function getJikanEpisodes(malId, maxPages = 20) { const rows = []; for (let page = 1; page <= maxPages; page++) { try { const json = await requestJson(`${JIKAN_URL}/anime/${malId}/episodes?page=${page}`, { retries: 2, cacheKey: `jk:e:${malId}:${page}` }); const batch = Array.isArray(json?.data) ? json.data : []; rows.push(...batch); if (batch.length < 100) break; } catch { break; } } return rows; }
export async function getAniZipMapping(malId) { const key = `az:m:${malId}`, cached = getCached(key); if (cached !== undefined) return cached; try { const json = await requestJson(`${ANIZIP_URL}/mappings?mal_id=${encodeURIComponent(malId)}`, { retries: 2, cacheKey: key }); return setCached(key, json?.mappings || json || {}); } catch { setCached(key, null); return null; } }
export async function getAniZipEpisodes(anilistId, maxPages = 20) { const all = [], seen = new Set(); for (let page = 1; page <= maxPages; page++) { try { const suffix = page === 1 ? "" : `&page=${page}`; const json = await requestJson(`${ANIZIP_URL}/episodes?anilist_id=${encodeURIComponent(anilistId)}${suffix}`, { retries: 2, cacheKey: `az:e:${anilistId}:${page}` }); const batch = Array.isArray(json?.episodes) ? json.episodes : Object.values(json?.episodes || {}); let added = 0; for (const item of batch) { const season = Number(item?.seasonNumber ?? item?.season ?? 1) || 1; const episode = Number(item?.episodeNumber ?? item?.number ?? item?.episode); const air = item?.airDateUtc ?? item?.airDate ?? item?.airdate ?? ""; const key = `${season}:${episode}:${air}`; if (Number.isInteger(episode) && episode > 0 && !seen.has(key)) { seen.add(key); all.push(item); added++; } } if (!added) break; } catch { break; } } return all; }
export async function discoverTvGraph(startMalId, rootJikan, maxNodes = 24) { const queue = [Number(startMalId)], seen = new Set(), result = new Map(); while (queue.length && result.size < maxNodes) { const malId = Number(queue.shift()); if (!malId || seen.has(malId)) continue; seen.add(malId); const [node, jikan] = await Promise.all([getAniListByMal(malId), malId === Number(startMalId) ? Promise.resolve(rootJikan) : getJikanAnime(malId)]); const tvNode = node && String(node.format).toUpperCase() === "TV" ? node : null; const tvJikan = jikan && String(jikan.type).toUpperCase() === "TV" ? jikan : (tvNode ? aniListToJikan(tvNode) : null); if (!tvNode && !tvJikan) continue; result.set(malId, { node: tvNode, jikan: tvJikan }); for (const edge of tvNode?.relations?.edges || []) { const rel = String(edge.relationType || "").toUpperCase(), child = edge.node, childMal = Number(child?.idMal || 0); if (["PREQUEL","SEQUEL"].includes(rel) && childMal && String(child?.format || "").toUpperCase() === "TV" && !seen.has(childMal)) queue.push(childMal); } for (const rel of jikan?.relations || []) { if (!/^(Sequel|Prequel)$/i.test(String(rel.relation || ""))) continue; for (const child of rel.entry || []) if (Number(child?.mal_id) && !seen.has(Number(child.mal_id))) queue.push(Number(child.mal_id)); } } return [...result.values()]; }
