export const ARM_URL = "https://arm.haglund.dev/api/v2/ids";
export const ANIZIP_URL = "https://api.ani.zip/mappings";
export const MALSYNC_URL = "https://api.malsync.moe/mal/anime";
export const ANIBRIDGE_URL = "https://mappings.anibridge.eliasbenb.dev/api/v3/mappings";
export const WIKIDATA_SPARQL_URL = "https://query.wikidata.org/sparql";
export const TVDB_WEB_SEARCH_URL = "https://api4.thetvdb.com/web/search/queries";
export const TVDB_SERIES_URL = "https://thetvdb.com/series/";
export const TVDB_READER_URL = "https://r.jina.ai/http://thetvdb.com/series/";
export const KITSU_URL = "https://kitsu.io/api/edge/anime";
export const ANILIST_URL = "https://graphql.anilist.co";
export const FETCH_TIMEOUT_MS = 8000;
export const CACHE_TTL_MS = 24 * 60 * 60 * 1000;
export const NEGATIVE_CACHE_TTL_MS = 60 * 60 * 1000;
export const MAX_CONCURRENCY = 6;
export const MAX_ROOT_RELATION_DEPTH = 8;
export const cache=new Map(),verifiedKitsuCache=new Map(),tvdbCache=new Map(),rootTvdbCache=new Map(),anibridgeTvdbCache=new Map(),wikidataTvdbCache=new Map(),wikidataTitleTvdbCache=new Map(),tvdbWebSearchCache=new Map(),tvdbSeriesPageCache=new Map();
