import { getCached, setCached, requestJson } from "./http.js";
const ANILIST_URL="https://graphql.anilist.co",JIKAN_URL="https://api.jikan.moe/v4",ANIZIP_URL="https://api.ani.zip/v1";
const ANILIST_FIELDS=`id idMal format status episodes season seasonYear title{romaji english native} synonyms startDate{year month day} endDate{year month day} relations{edges{relationType node{id idMal format status episodes season seasonYear title{romaji english native} synonyms startDate{year month day} endDate{year month day}}}}`;
export async function getAniListByMal(malId){const key=`al:${malId}`,cached=getCached(key);if(cached!==undefined)return cached;const query=`query($idMal:Int){Media(idMal:$idMal,type:ANIME){${ANILIST_FIELDS}}}`;try{const json=await requestJson(ANILIST_URL,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({query,variables:{idMal:Number(malId)}}),retries:2,cacheKey:key});return setCached(key,json?.data?.Media||null);}catch{setCached(key,null);return null;}}
export function aniListToJikan(node){return node?{mal_id:Number(node.idMal),type:"TV",episodes:Number(node.episodes)||null,title:node.title?.romaji||node.title?.english||node.title?.native||`MAL ${node.idMal}`,title_english:node.title?.english||null,title_japanese:node.title?.native||null,title_synonyms:Array.isArray(node.synonyms)?node.synonyms:[],aired:{from:dateParts(node.startDate),to:dateParts(node.endDate)},year:Number(node.seasonYear)||null}:null;}
function dateParts(x){return x?.year&&x?.month&&x?.day?`${String(x.year).padStart(4,"0")}-${String(x.month).padStart(2,"0")}-${String(x.day).padStart(2,"0")}T00:00:00.000Z`:null;}
export async function getJikanAnime(malId){const key=`jk:a:${malId}`,cached=getCached(key);if(cached!==undefined)return cached;try{const json=await requestJson(`${JIKAN_URL}/anime/${malId}/full`,{retries:2,cacheKey:key});return setCached(key,json?.data||null);}catch{setCached(key,null);return null;}}
export async function searchJikanAnime(query,limit=10){const normalized=String(query||"").trim();if(!normalized)return[];const key=`jk:s:${normalized.toLowerCase()}:${limit}`,cached=getCached(key);if(cached!==undefined)return Array.isArray(cached)?cached:[];try{const json=await requestJson(`${JIKAN_URL}/anime?q=${encodeURIComponent(normalized)}&type=tv&limit=${Math.min(25,Math.max(1,Number(limit)||10))}`,{retries:2,cacheKey:key});const rows=Array.isArray(json?.data)?json.data:[];return setCached(key,rows);}catch{setCached(key,[]);return[];}}
export async function getJikanEpisodes(malId,maxPages=20){const rows=[];for(let page=1;page<=maxPages;page++){try{const json=await requestJson(`${JIKAN_URL}/anime/${malId}/episodes?page=${page}`,{retries:2,cacheKey:`jk:e:${malId}:${page}`}),batch=Array.isArray(json?.data)?json.data:[];rows.push(...batch);if(batch.length<100)break;}catch{break;}}return rows;}
export async function getAniZipMapping(malId){const key=`az:m:${malId}`,cached=getCached(key);if(cached!==undefined)return cached;try{const json=await requestJson(`${ANIZIP_URL}/mappings?mal_id=${encodeURIComponent(malId)}`,{retries:2,cacheKey:key});return setCached(key,json?.mappings||json||{});}catch{setCached(key,null);return null;}}
export function extractAniZipEpisodeBatch(json){if(Array.isArray(json?.episodes))return json.episodes;if(json?.episodes&&typeof json.episodes==="object")return Object.values(json.episodes);return[];}
export async function getTvMazeEpisodes(imdbId){const normalizedImdbId=String(imdbId||"").trim();if(!/^tt\d+$/i.test(normalizedImdbId))return[];const key=`tm:e:${normalizedImdbId}`,cached=getCached(key);if(cached!==undefined)return cached;try{const show=await requestJson(`https://api.tvmaze.com/lookup/shows?imdb=${encodeURIComponent(normalizedImdbId)}`,{retries:2,cacheKey:`tm:s:${normalizedImdbId}`}),showId=extractTvMazeShowId(show);if(!showId)return setCached(key,[]);const episodesJson=await requestJson(`https://api.tvmaze.com/shows/${showId}/episodes`,{retries:2,cacheKey:`tm:e:${showId}`}),rows=extractTvMazeEpisodeBatch(episodesJson).map(normalizeTvMazeEpisode).filter(Boolean);return setCached(key,rows);}catch{setCached(key,[]);return[];}}
export function extractTvMazeShowId(value){const id=Number(value?.id);return Number.isInteger(id)&&id>0?id:0;}
export function extractTvMazeEpisodeBatch(value){return Array.isArray(value)?value:Array.isArray(value?.episodes)?value.episodes:[];}
function normalizeTvMazeEpisode(item){const number=Number(item?.number);if(!Number.isInteger(number)||number<=0)return null;const sourceSeason=Number(item?.season)||1,title=String(item?.name||`Episode ${number}`).trim(),released=validEpisodeDate(item?.airdate,item?.airtime);if(!released||new Date(released).getTime()>Date.now())return null;const absoluteEpisodeNumber=extractAbsoluteEpisodeNumber(title);return{number,sourceSeason,absoluteEpisodeNumber,title,released,thumbnail:item?.image?.original||item?.image?.medium||null};}
function extractAbsoluteEpisodeNumber(title){const match=String(title||"").match(/\b(?:episode|ep\.)\s*#?\s*(\d+)\b/i);return match?Number(match[1]):0;}
function validEpisodeDate(airdate,airtime){if(!airdate)return null;const date=new Date(airtime?`${airdate}T${airtime}:00Z`:`${airdate}T00:00:00Z`);return Number.isNaN(date.getTime())?null:date.toISOString();}
export async function getAniZipEpisodes(anilistId){const key=`az:e:${anilistId}`,cached=getCached(key);if(cached!==undefined)return cached;try{const json=await requestJson(`${ANIZIP_URL}/episodes?anilist_id=${encodeURIComponent(anilistId)}`,{retries:2,cacheKey:key});return setCached(key,extractAniZipEpisodeBatch(json));}catch{setCached(key,[]);return[];}}
export function franchiseSearchQuery(jikan){const values=[jikan?.title_english,jikan?.title,jikan?.title_japanese,...(jikan?.title_synonyms||[])].filter(Boolean).map(String);for(const value of values){const stripped=value.replace(/\b(?:season|s)\s*\d+\b/gi," ").replace(/\b(?:[2-9]|10)(?:st|nd|rd|th)?\s+season\b/gi," ").replace(/\b(?:ii|iii|iv|v|vi|vii|viii|ix|x)\b/gi," ").replace(/\b(?:part|cour)\s*[12]\b/gi," ").replace(/\s+/g," ").trim();if(stripped.length>=3)return stripped;}return"";}
export function sameFranchiseTitle(a,b){const normalize=value=>String(value||"").toLowerCase().replace(/[：:!?,.\-–—]+/g," ").replace(/\s+/g," ").trim();const aa=[a?.title_english,a?.title,a?.title_japanese,...(a?.title_synonyms||[])].filter(Boolean).map(normalize),bb=[b?.title_english,b?.title,b?.title_japanese,...(b?.title_synonyms||[])].filter(Boolean).map(normalize);return aa.some(x=>bb.some(y=>x===y||x.startsWith(`${y} `)||y.startsWith(`${x} `)))}
export async function discoverTvGraph(startMalId,rootJikan,maxNodes=24){const queue=[Number(startMalId)],seen=new Set(),result=new Map(),CONCURRENCY=4;while(queue.length&&result.size<maxNodes){const batch=[];while(queue.length&&batch.length<CONCURRENCY&&result.size+batch.length<maxNodes){const malId=Number(queue.shift());if(!malId||seen.has(malId))continue;seen.add(malId);batch.push(malId);}const resolved=await Promise.all(batch.map(async malId=>{const[node,jikan]=await Promise.all([getAniListByMal(malId),malId===Number(startMalId)?Promise.resolve(rootJikan):getJikanAnime(malId)]),tvNode=node&&String(node.format).toUpperCase()==="TV"?node:null,tvJikan=jikan&&String(jikan.type).toUpperCase()==="TV"?jikan:(tvNode?aniListToJikan(tvNode):null);return{malId,tvNode,tvJikan};}));for(const item of resolved){const{malId,tvNode,tvJikan}=item;if(!tvNode&&!tvJikan)continue;result.set(malId,{node:tvNode,jikan:tvJikan});for(const edge of tvNode?.relations?.edges||[]){const rel=String(edge.relationType||"").toUpperCase(),child=edge.node,childMal=Number(child?.idMal||0);if(["PREQUEL","SEQUEL"].includes(rel)&&childMal&&!seen.has(childMal))queue.push(childMal);}for(const rel of item.tvJikan?.relations||[]){if(!/^(Sequel|Prequel)$/i.test(String(rel?.relation||"")))continue;for(const child of rel.entry||[]){const childMal=Number(child?.mal_id||0);if(childMal&&!seen.has(childMal))queue.push(childMal);}}}
if(result.size<maxNodes&&rootJikan&&/(?:season\s*[2-9]|\b[2-9](?:st|nd|rd|th)?\s+season\b|\b(?:ii|iii|iv|v|vi|vii|viii|ix|x)\b)/i.test([rootJikan.title_english,rootJikan.title,...(rootJikan.title_synonyms||[])].filter(Boolean).join(" "))){const query=franchiseSearchQuery(rootJikan);if(query){const searchRows=await searchJikanAnime(query,10);const candidates=searchRows.filter(row=>Number(row?.mal_id)>0&&Number(row.mal_id)!==Number(startMalId)&&sameFranchiseTitle(rootJikan,row));const limited=candidates.slice(0,Math.max(0,maxNodes-result.size));const resolved=await Promise.all(limited.map(async row=>{const[node,jikan]=await Promise.all([getAniListByMal(row.mal_id),getJikanAnime(row.mal_id)]);const tvNode=node&&String(node.format).toUpperCase()==="TV"?node:null,tvJikan=jikan&&String(jikan.type).toUpperCase()==="TV"?jikan:(tvNode?aniListToJikan(tvNode):null);return tvNode||tvJikan?{malId:Number(row.mal_id),tvNode,tvJikan}:null;}));for(const item of resolved.filter(Boolean))result.set(item.malId,{node:item.tvNode,jikan:item.tvJikan});}}
return[...result.values()];}
