export function enrichMeta(meta,root,rootAniList=null,seasonGroups=[]){const enriched={...meta},extras={...(meta?.app_extras||{})},releaseInfo=formatReleaseInfo(root?.aired?.from,root?.aired?.to);if(releaseInfo)enriched.releaseInfo=releaseInfo;if(root?.aired?.from)enriched.released=toIsoDate(root.aired.from);if(root?.aired?.to)enriched.lastAirDate=toIsoDate(root.aired.to);if(root?.status)enriched.status=String(root.status);if(Number(root?.duration)>0)enriched.runtime=`${Number(root.duration)}m`;const country=normalizeCountry(rootAniList?.countryOfOrigin);if(country)enriched.country=country;if(country==="JP")enriched.language="Japanese";if(rootAniList?.bannerImage)enriched.background=rootAniList.bannerImage;const certification=normalizeCertification(root?.rating);if(certification){enriched.ageRating=certification;extras.certificationLocal=certification;extras.certification=certification;}const cast=extractCast(root?.characters);if(cast.length){enriched.cast=cast.map(person=>person.name);extras.cast=cast;}const trailers=extractTrailers(root?.trailer);if(trailers.length)enriched.trailers=trailers;const seasonPosters=buildSeasonPosters(seasonGroups,root,rootAniList);if(Object.keys(seasonPosters).length)extras.seasonPosters=seasonPosters;enriched.videos=(meta?.videos||[]).map(video=>{const poster=seasonPosters[String(video?.season)],runtime=video?.runtime||enriched.runtime;return{...video,...(poster?{seasonPoster:poster}:{}),...(runtime?{runtime}:{} )};});if(Object.keys(extras).length)enriched.app_extras=extras;return enriched;}
export function formatReleaseInfo(start,end){const startYear=yearOf(start);if(!startYear)return null;const endYear=yearOf(end);return endYear&&endYear>=startYear?`${startYear}-${endYear}`:`${startYear}-`;}
export function normalizeCertification(value){const rating=String(value||"").trim();if(!rating||/^none$/i.test(rating))return null;if(/^R\s*-\s*17\+/i.test(rating))return"R";if(/^R\+\s*-/i.test(rating))return"R+";if(/^PG-13/i.test(rating))return"PG-13";if(/^PG\s*-/i.test(rating))return"PG";if(/^G\s*-/i.test(rating))return"G";if(/^Rx/i.test(rating))return"Rx";return rating;}
function extractCast(characters){if(!Array.isArray(characters))return[];const people=[];for(const entry of characters){const characterName=String(entry?.character?.name||"").trim(),actors=Array.isArray(entry?.voice_actors)?entry.voice_actors:[],preferred=actors.find(actor=>/^Japanese$/i.test(String(actor?.language||"")))||actors[0],person=preferred?.person,name=String(person?.name||characterName||"").trim();if(!name)continue;people.push({name,character:characterName||undefined,photo:person?.images?.jpg?.image_url||entry?.character?.images?.jpg?.image_url||undefined});}const seen=new Set();return people.filter(person=>{const key=person.name.toLowerCase();if(seen.has(key))return false;seen.add(key);return true;});}
function extractTrailers(trailer){const youtubeId=String(trailer?.youtube_id||"").trim();if(!youtubeId)return[];return[{id:youtubeId,key:youtubeId,source:youtubeId,name:"Trailer",site:"YouTube",type:"Trailer",official:true}];}
function buildSeasonPosters(groups,root,rootAniList){const posters={};for(const group of Array.isArray(groups)?groups:[]){const season=Number(group?.season);if(!Number.isInteger(season)||season<=0)continue;const entry=Array.isArray(group?.entries)?group.entries[0]:null,nodePoster=entry?.node?.coverImage?.extraLarge||entry?.node?.coverImage?.large,jikanPoster=entry?.jikan?.images?.jpg?.large_image_url||entry?.jikan?.images?.jpg?.image_url,rootPoster=season===1?root?.images?.jpg?.large_image_url||root?.images?.jpg?.image_url||rootAniList?.coverImage?.extraLarge||rootAniList?.coverImage?.large:null,poster=nodePoster||jikanPoster||rootPoster;if(poster)posters[String(season)]=poster;}return posters;}
function normalizeCountry(value){const country=String(value||"").trim().toUpperCase();return/^[A-Z]{2}$/.test(country)?country:null;}
function yearOf(value){const match=String(value||"").match(/^(\d{4})/);return match?Number(match[1]):0;}
function toIsoDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString();}
