export function enrichMeta(meta,root,rootAniList=null,seasonGroups=[]){const enriched={...meta},extras={...(meta?.app_extras||{})},releaseInfo=formatReleaseInfo(root?.aired?.from,latestKnownDate(root,meta?.videos,seasonGroups));if(releaseInfo)enriched.releaseInfo=releaseInfo;const released=toIsoDate(root?.aired?.from);if(released)enriched.released=released;const lastAirDate=latestKnownDate(root,meta?.videos,seasonGroups);if(lastAirDate)enriched.lastAirDate=toIsoDate(lastAirDate);if(root?.status)enriched.status=String(root.status);if(Number(root?.duration)>0)enriched.runtime=`${Number(root.duration)}m`;const country=normalizeCountry(rootAniList?.countryOfOrigin);if(country)enriched.country=country;if(country==="JP")enriched.language="Japanese";if(rootAniList?.bannerImage)enriched.background=rootAniList.bannerImage;const certification=normalizeCertification(root?.rating);if(certification){enriched.ageRating=certification;extras.certificationLocal=certification;extras.certification=certification;}const networks=extractNetworks(root);if(networks.length)enriched.network=networks.join(", ");const producers=extractProducers(root);if(producers.length)extras.producers=producers;const studios=extractStudios(rootAniList);if(studios.length){enriched.studios=studios;extras.studios=studios;}const cast=extractCast(rootAniList?.characters?.edges,root?.characters);if(cast.length){enriched.cast=cast.map(person=>person.name);extras.cast=cast;}const trailers=extractTrailers(rootAniList?.trailer,root?.trailer);if(trailers.length)enriched.trailers=trailers;const streamingEpisodes=extractStreamingEpisodes(rootAniList?.streamingEpisodes);if(streamingEpisodes.length)extras.streamingEpisodes=streamingEpisodes;const recommendations=extractRecommendations(rootAniList?.recommendations?.nodes);if(recommendations.length){enriched.recommendations=recommendations;extras.recommendations=recommendations;}const externalLinks=extractExternalLinks(rootAniList?.externalLinks);if(externalLinks.length)enriched.links=[...(Array.isArray(enriched.links)?enriched.links:[]),...externalLinks.filter(link=>!(enriched.links||[]).some(existing=>existing.url===link.url))];const seasonPosters=buildSeasonPosters(seasonGroups,root,rootAniList);if(Object.keys(seasonPosters).length)extras.seasonPosters=seasonPosters;enriched.videos=(meta?.videos||[]).map(video=>{const poster=seasonPosters[String(video?.season)],runtime=video?.runtime||enriched.runtime;return{...video,...(poster?{seasonPoster:poster}:{}),...(runtime?{runtime}:{} )};});if(Object.keys(extras).length)enriched.app_extras=extras;return enriched;}
export function formatReleaseInfo(start,end){const startYear=yearOf(start);if(!startYear)return null;const endYear=yearOf(end);return endYear&&endYear>=startYear?`${startYear}-${endYear}`:`${startYear}-`;}
export function normalizeCertification(value){const rating=String(value||"").trim();if(!rating||/^none$/i.test(rating))return null;if(/^R\s*-\s*17\+/i.test(rating))return"R";if(/^R\+\s*-/i.test(rating))return"R+";if(/^PG-13/i.test(rating))return"PG-13";if(/^PG\s*-/i.test(rating))return"PG";if(/^G\s*-/i.test(rating))return"G";if(/^Rx/i.test(rating))return"Rx";return rating;}
function extractNetworks(root){const value=String(root?.broadcast?.string||"").trim();return value?[value]:[];}
function extractProducers(root){return(Array.isArray(root?.producers)?root.producers:[]).map(producer=>String(producer?.name||"").trim()).filter(Boolean).filter((name,index,array)=>array.findIndex(value=>value.toLowerCase()===name.toLowerCase())===index);}
function extractStudios(rootAniList){return(Array.isArray(rootAniList?.studios?.nodes)?rootAniList.studios.nodes:[]).map(studio=>String(studio?.name||"").trim()).filter(Boolean).filter((name,index,array)=>array.findIndex(value=>value.toLowerCase()===name.toLowerCase())===index);}
function extractCast(edges,jikanCharacters){const people=[];for(const entry of Array.isArray(edges)?edges:[]){const characterName=String(entry?.node?.name?.full||"").trim(),voice=Array.isArray(entry?.voiceActors)?entry.voiceActors[0]:null,name=String(voice?.name?.full||characterName||"").trim();if(!name)continue;people.push({name,character:characterName||undefined,photo:voice?.image?.large||entry?.node?.image?.large||undefined,role:String(entry?.role||"").trim()||undefined});}if(!people.length)for(const entry of Array.isArray(jikanCharacters)?jikanCharacters:[]){const characterName=String(entry?.character?.name||"").trim(),actors=Array.isArray(entry?.voice_actors)?entry.voice_actors:[],preferred=actors.find(actor=>/^Japanese$/i.test(String(actor?.language||"")))||actors[0],person=preferred?.person,name=String(person?.name||characterName||"").trim();if(name)people.push({name,character:characterName||undefined,photo:person?.images?.jpg?.image_url||entry?.character?.images?.jpg?.image_url||undefined,role:undefined});}const seen=new Set();return people.filter(person=>{const key=person.name.toLowerCase();if(seen.has(key))return false;seen.add(key);return true;}).slice(0,30);}
function extractTrailers(anilistTrailer,jikanTrailer){const trailers=[];const site=String(anilistTrailer?.site||"").trim(),id=String(anilistTrailer?.id||"").trim();if(id&&site)trailers.push({id,key:id,source:id,name:"Trailer",site,type:"Trailer",official:true,thumbnail:anilistTrailer?.thumbnail||undefined,url:site.toLowerCase()==="youtube"?`https://www.youtube.com/watch?v=${id}`:undefined});const youtubeId=String(jikanTrailer?.youtube_id||"").trim();if(youtubeId&&!trailers.some(trailer=>trailer.key===youtubeId))trailers.push({id:youtubeId,key:youtubeId,source:youtubeId,name:"Trailer",site:"YouTube",type:"Trailer",official:true,thumbnail:jikanTrailer?.images?.maximum_image_url||jikanTrailer?.images?.large_image_url||undefined,url:`https://www.youtube.com/watch?v=${youtubeId}`});return trailers.slice(0,10);}
function extractStreamingEpisodes(episodes){return(Array.isArray(episodes)?episodes:[]).filter(episode=>episode?.url).map(episode=>({title:String(episode.title||"Streaming Video"),site:String(episode.site||""),url:String(episode.url),thumbnail:episode.thumbnail||undefined})).slice(0,10);}
function extractRecommendations(nodes){const result=[];for(const node of Array.isArray(nodes)?nodes:[]){const media=node?.mediaRecommendation;if(!media)continue;const idMal=Number(media.idMal||0),id=idMal>0?`mal:${idMal}`:`anilist:${media.id}`,name=String(media.title?.english||media.title?.romaji||media.title?.native||"").trim();if(!name||result.some(item=>item.id===id))continue;result.push({id,type:"series",name,poster:media.coverImage?.large||undefined});}return result.slice(0,10);}
function extractExternalLinks(links){return(Array.isArray(links)?links:[]).filter(link=>link?.url).map(link=>({name:String(link.site||""),category:String(link.type||"database").toLowerCase(),url:String(link.url)}));}
function buildSeasonPosters(groups,root,rootAniList){const posters={};for(const group of Array.isArray(groups)?groups:[]){const season=Number(group?.season);if(!Number.isInteger(season)||season<=0)continue;const entry=Array.isArray(group?.entries)?group.entries[0]:null,nodePoster=entry?.node?.coverImage?.extraLarge||entry?.node?.coverImage?.large,jikanPoster=entry?.jikan?.images?.jpg?.large_image_url||entry?.jikan?.images?.jpg?.image_url,rootPoster=season===1?root?.images?.jpg?.large_image_url||root?.images?.jpg?.image_url||rootAniList?.coverImage?.extraLarge||rootAniList?.coverImage?.large:null,poster=nodePoster||jikanPoster||rootPoster;if(poster)posters[String(season)]=poster;}return posters;}
function latestKnownDate(root,videos,seasonGroups){const dates=[];if(root?.aired?.to)dates.push(root.aired.to);for(const group of Array.isArray(seasonGroups)?seasonGroups:[])for(const entry of Array.isArray(group?.entries)?group.entries:[])if(entry?.jikan?.aired?.to)dates.push(entry.jikan.aired.to);for(const video of Array.isArray(videos)?videos:[])if(video?.released)dates.push(video.released);return dates.filter(Boolean).sort((a,b)=>new Date(b)-new Date(a))[0]||root?.aired?.from||null;}
function normalizeCountry(value){const country=String(value||"").trim().toUpperCase();return/^[A-Z]{2}$/.test(country)?country:null;}
function yearOf(value){const match=String(value||"").match(/^(\d{4})/);return match?Number(match[1]):0;}
function toIsoDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString();}
